theme: jekyll-theme-minimal
title: Krzysztof Rogowski # your name (or website title) here
logo: "/images/ProfileImage_Krzysztof.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Solution Architecture | Data Modeling | Cloud Data Warehousing | Enterprise BI Strategy | Data Governance | Senior Engineering Leadership
  <br>
  <br>
  <br>
  <a href="https://www.linkedin.com/in/krzysztof-rogowski-1199036">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
  <br><br>
  
##KR: remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3LGNXMWLWJ # your Google Analytics tracking ID here
navigation:
  - title: Strategic Overview
    url: /
  - title: Architectural Case Studies
    url: /architectural-case-studies.html
  - title: Solutions & Capabilities
    url: /solutions-and-capabilities.html
#  - title: Insights
#    url: /insights.html
  - title: Work With Me
    url: /work-with-me.html
